-- CreateEnum
CREATE TYPE "OrigenCliente" AS ENUM ('CLIENTE_EMPRESA', 'CLIENTE_ECOMMERCE');

-- CreateEnum
CREATE TYPE "EcommerceClienteTipo" AS ENUM ('NATURAL', 'EMPRESA');

-- Enable uuid generation for Prisma defaults
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Defaults for ids generated by Prisma
ALTER TABLE "CrmCotizacion" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_usuario" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_cliente" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_direccion" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_carrito" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_carrito_item" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_cotizacion" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_cotizacion_item" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_pedido" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_pedido_item" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_pago" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "ecommerce_notificacion" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();

-- Add origin tag to CRM cotizacion mirror
ALTER TABLE "CrmCotizacion" ADD COLUMN "origenCliente" "OrigenCliente";

-- Ecommerce usuario state
ALTER TABLE "ecommerce_usuario" ADD COLUMN "estado" TEXT NOT NULL DEFAULT 'ACTIVO';

-- Ecommerce cliente extra profile fields
ALTER TABLE "ecommerce_cliente" ADD COLUMN "tipo" "EcommerceClienteTipo";
ALTER TABLE "ecommerce_cliente" ADD COLUMN "rut" TEXT;
ALTER TABLE "ecommerce_cliente" ADD COLUMN "apellidos" TEXT;

-- Ecommerce direccion extra fields
ALTER TABLE "ecommerce_direccion" ADD COLUMN "etiqueta" TEXT;
ALTER TABLE "ecommerce_direccion" ADD COLUMN "numero" TEXT;
ALTER TABLE "ecommerce_direccion" ADD COLUMN "depto" TEXT;
ALTER TABLE "ecommerce_direccion" ADD COLUMN "codigoPostal" TEXT;

-- Legacy CRM clienteId columns (optional, no FK)
ALTER TABLE "ecommerce_carrito" ADD COLUMN "clienteId" TEXT;
ALTER TABLE "ecommerce_cotizacion" ADD COLUMN "clienteId" TEXT;
ALTER TABLE "ecommerce_pedido" ADD COLUMN "clienteId" TEXT;

CREATE INDEX "ecommerce_carrito_clienteId_legacy_idx" ON "ecommerce_carrito"("clienteId");
CREATE INDEX "ecommerce_cotizacion_clienteId_legacy_idx" ON "ecommerce_cotizacion"("clienteId");
CREATE INDEX "ecommerce_pedido_clienteId_legacy_idx" ON "ecommerce_pedido"("clienteId");

-- CRM mirror links from ecommerce
ALTER TABLE "ecommerce_cotizacion" ADD COLUMN "crmCotizacionId" TEXT;
ALTER TABLE "ecommerce_pedido" ADD COLUMN "crmCotizacionId" TEXT;

CREATE UNIQUE INDEX "ecommerce_cotizacion_crmCotizacionId_key" ON "ecommerce_cotizacion"("crmCotizacionId");

ALTER TABLE "ecommerce_cotizacion" ADD CONSTRAINT "ecommerce_cotizacion_crmCotizacionId_fkey" FOREIGN KEY ("crmCotizacionId") REFERENCES "CrmCotizacion"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ecommerce_pedido" ADD CONSTRAINT "ecommerce_pedido_crmCotizacionId_fkey" FOREIGN KEY ("crmCotizacionId") REFERENCES "CrmCotizacion"("id") ON DELETE SET NULL ON UPDATE CASCADE;
